databases:
  - name: clearmyspam-db
    databaseName: clearmyspam
    user: clearmyspam
    plan: basic-1gb
    diskSizeGB: 5
    region: oregon

services:
  - type: web
    name: clearmyspam
    runtime: ruby
    plan: standard
    region: oregon
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate && bundle exec rails blogs:sync_metadata"
    startCommand: "bundle exec rails server"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: clearmyspam-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
  - type: worker
    name: clearmyspam-worker
    plan: starter
    runtime: ruby
    region: oregon
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec good_job start"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: clearmyspam-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false